name: "sealix-network"
version: "1.0"

client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'

channels:
  mychannel:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    tlsCACerts:
      path: /path/to/orderer/tls/ca.crt

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      path: /path/to/peer/tls/ca.crt

certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca.org1.example.com
    tlsCACerts:
      path: /path/to/ca/tls/ca.crt
    registrar:
      - enrollId: admin
        enrollSecret: adminpw